### ISSUE TITLE
Measure performance hit by using Lua filters instead of standard prio filter

### ISSUE THREAD

**Issue by kr0st** [kr0st/fplog#21]
I.e. how much slower is using Lua filters compared with prio filters?

**Comment by Raven990** [comment]
## Performance test results:
Priority filter: 
10 iterations with 100000 messages are done in 8.01495 seconds
12476 messages/second

Lua filter:
10 iterations with 100000 messages are done in 302.798 seconds
330 messages/second

Priority filter faster than Lua for 3777.91%

**Comment by kr0st** [comment]
That's quite a performance hit... Will see if that could be improved in future.
